### PR TITLE
Added pinch to zoom

### PR DESCRIPTION
**Pull request by YWinters**
I added a pinch gesture recognizer to enable zooming. In this fork zooming is enabled by default, you may want to edit this in the future.

### CODE REVIEW

**Comment by billychasen** [comment]
Thanks for this. By the way, if your first gesture is to pinch the screen, it won't work. You can fix this by initially setting _effectiveScale = 1.0

**Comment by omergul123** [comment]
@YWinters thanks for the PR, could you please open the PR for the develop branch? Then I will merge and release a new version.

**Comment by mythodeia** [comment]
to make this work you need to init the gesture recognizer with this
```
self.pinchGesture = [[UIPinchGestureRecognizer alloc] initWithTarget:self action:@selector(handlePinchGesture:)];
```

**Comment by RyanKim01** [comment]
@YWinters Thank you so much for your update. It works fantastic. I have 2 questions. 1. How do I limit max scale? 2. When I zoom in or zoom out, it happens 0.5 sec after my action's done. In other words, zooming in & out action is not instantaneous. Is there a way to fix this problem?

**Comment by DrustZ** [comment]
This function is so essential. Please merge it~

**Comment by YWinters** [comment]
I created a pull request on the develop branch

**Comment by RyanKim01** [comment]
@YWinters Do you mind answering my two questions above? I've been trying hard to solve but could not get solutions.

**Comment by YWinters** [comment]
@RyanKim01 I added a maxScale property to my latest commit (10 minutes ago).. thanks for the suggestion. On the other hand I don't have any clue how to fix to 0.5 seconds delay.. neither did I find it disrupting. Perhaps you can take a look at it?

**Pull request closed without merging**
