### PR TITLE
*** Add the Judgment for the camera available. Use for the iPod touch.

### PR DESCRIPTION
**Pull request by liyalin**
*** use example :if ([self.camera isCameraAvailable]){ *code here*}

### CODE REVIEW

**Comment by omergul123** [comment]
@liyalin thanks for the pr, could you please reopen it on develop branch?

**Comment by liyalin** [comment]
@omergul123 Emm, Sorry for that. But how to change to the develop branch？

**Comment by omergul123** [comment]
@liyalin just cancel the current one, and reopen a new one on develop branch.

**Comment by omergul123** [comment]
Merged locally due to conflicts. Thanks!

**Pull request closed without merging**
