### PR TITLE
Adds pinch to zoom gesture

### PR DESCRIPTION
**Pull request by kylebrowning**
Fixes #58

### CODE REVIEW

**Comment by kylebrowning** [comment]
Looks like my client removed spaces and lines too, damnit.

**Comment by kylebrowning** [comment]
There we go, fixed it.

**Comment by kylebrowning** [comment]
Let me know if you need anything else @omergul123

**Comment by omergul123** [comment]
@kylebrowning thanks, looks good, only thing is instead of using a constant 10.0f as the maxScale, shouldn't we just use this:

 ```device.activeFormat.videoMaxZoomFactor```

**Comment by kylebrowning** [comment]
@omergul123  Done.

**Comment by kylebrowning** [comment]
@omergul123 Merge soon?

**Comment by omergul123** [comment]
@kylebrowning done after tweaking some small things. Thanks!

**Pull request merged**
