### PR TITLE
Added tap to focus.

### PR DESCRIPTION
**Pull request by sachinkesiraju**
Added a noticeable missing feature to an otherwise fantastic control. Lets the user tap on the camera view to focus the image.

### CODE REVIEW

**Comment by omergul123** [comment]
Thanks for your contribution @sachinkesiraju , could you please reopen a pull request on "develop" branch?

**Comment by omergul123** [comment]
Thanks for your contribution @sachinkesiraju , could you please reopen a pull request on "develop" branch?

**Comment by sachinkesiraju** [comment]
Hi @omergul123 , I opened a pull request on the develop branch a few days ago. Check it out and let me  know what you think.
Thanks

**Comment by omergul123** [comment]
@sachinkesiraju  It looks great, I'll merge and add some extra features in this week, just didn't have time previous week.

**Comment by sachinkesiraju** [comment]
Sure, no problem. Thanks.

**Pull request closed without merging**
