### PR TITLE
Added changes to develop branch to support pinch to zoom

### PR DESCRIPTION
**Pull request by YWinters**

### CODE REVIEW

**Comment by kylebrowning** [comment]
Your spacing is different than the original file so it makes it so hard to see what you actually changed...

**Comment by omergul123** [comment]
Agreed with @kylebrowning, can you make remove the unnecessary changes and update the PR @YWinters ?

**Comment by omergul123** [comment]
@YWinters any update?

**Comment by kylebrowning** [comment]
I fixed it is #76

**Comment by kylebrowning** [comment]
So you can close this one.

**Pull request closed without merging**
